# Generated by Django 5.2.15 on 2026-06-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
    ]
