# Generated by Django 5.2.15 on 2026-06-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
        migrations.AddField(
            model_name='reward',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
